# Generated by Django 4.0.5 on 2022-06-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_title', models.TextField(max_length=142, verbose_name='Название заметки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заметки')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='Дата, когда нужно выполнить заметку')),
                ('is_marked', models.IntegerField(default=0, verbose_name='Пометка "Важно"')),
                ('is_archived', models.IntegerField(default=0, verbose_name='Пометка "Архив"')),
                ('is_completed', models.IntegerField(default=0, verbose_name='Пометка "Выполнено"')),
                ('is_outdated', models.IntegerField(default=0, verbose_name='Пометка "Просрочено"')),
                ('checkbox1', models.TextField(blank=True, max_length=142, null=True, verbose_name='Подзадача №1')),
                ('checkbox2', models.TextField(blank=True, max_length=142, null=True, verbose_name='Подзадача №2')),
                ('checkbox3', models.TextField(blank=True, max_length=142, null=True, verbose_name='Подзадача №3')),
                ('checkbox4', models.TextField(blank=True, max_length=142, null=True, verbose_name='Подзадача №4')),
                ('checkbox5', models.TextField(blank=True, max_length=142, null=True, verbose_name='Подзадача №5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя')),
            ],
        ),
    ]
